---
title: "Preliminaries"
date: "Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: hide # class.source = "fold-hide" to hide code and add a button to show it
    df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
    code_download: true
    css: visual.css
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
  - \newcommand{\Wcal}{\mathcal{W}}
---

Go back to the [Contents](about.html) page.

<div style="color: #2c3e50; text-align: right;">
********  
<strong>Press Show to reveal the code chunks.</strong>  

********
</div>


```{r}
# Create a clipboard button on the rendered HTML page
source(here::here("clipboard.R")); clipboard
# Set seed for reproducibility
set.seed(1982) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}
```

```{r}
library(MetricGraph)
library(ggplot2)
library(reshape2)
library(plotly)

library(fmesher)
```


```{r}
capture.output(
  knitr::purl(here::here("functionality.Rmd"), output = here::here("functionality.R")),
  file = here::here("purl_log.txt")
)
source(here::here("functionality.R"))
```








:::: {style="display: grid; grid-template-columns: 400px 400px 400px; grid-column-gap: 1px;"}


::: {}

```{r, fig.height = 6, out.width = "100%", fig.cap = captioner("Time evolution of the absolute difference between the exact and approximate solution.")}
load(here::here("data_files/fem_basis_tadpole.RData"))
p_b1
```

:::


::: {}

```{r, fig.height = 6, out.width = "100%", fig.cap = captioner("Time evolution of the absolute difference between the exact and approximate solution.")}
#plot_3d_square_mesh(gets.mesh.and.FEM.on.rectangle(1, 1, 8)$mesh)
plot_3d_square_mesh_with_hat(gets.mesh.and.FEM.on.rectangle(1, 1, 6)$mesh, hat_nodes = c(1, 20, 43), hat_height = 1, hat_color = c("red", "red", "blue"), hat_alpha = 0.2)
```


:::



::: {}


```{r, fig.height = 6, out.width = "100%", fig.cap = captioner("Time evolution of the absolute difference between the exact and approximate solution.")}
#plot_3d_mesh_edges_faces(fm_rcdt_2d(globe = 3))
plot_3d_mesh_edges_faces_with_hat(
  fm_rcdt_2d(globe = 3),
  hat_nodes = c(1, 17, 37),
  hat_color = c("blue", "blue", "blue"),
  hat_height = 1,
  hat_alpha = 0.2
)
```


:::


::::




## For the error


:::: {style="display: grid; grid-template-columns: 400px 400px 400px; grid-column-gap: 1px;"}


::: {}

```{r, fig.height = 6, out.width = "100%", fig.cap = captioner("Time evolution of the absolute difference between the exact and approximate solution.")}
load(here::here("data_files/exp1_error_tadpole.RData"))
error_tadpole
```

:::


::: {}

```{r, fig.height = 6, out.width = "100%", fig.cap = captioner("Time evolution of the absolute difference between the exact and approximate solution.")}
load(here::here("data_files/exp_1_error_rectangle.RData"))
error_rectangle
```


:::



::: {}


```{r, fig.height = 6, out.width = "100%", fig.cap = captioner("Time evolution of the absolute difference between the exact and approximate solution.")}
load(here::here("data_files/exp_1_error_sphere.RData"))
error_sphere
```


:::


::::



## Functions values

## For the error


:::: {style="display: grid; grid-template-columns: 400px 400px 400px; grid-column-gap: 1px;"}


::: {}

```{r, fig.height = 6, out.width = "100%", fig.cap = captioner("Time evolution of the absolute difference between the exact and approximate solution.")}
load(here::here("data_files/exp1_f_tadpole.RData"))
f_tadpole
```

:::


::: {}

```{r, fig.height = 6, out.width = "100%", fig.cap = captioner("Time evolution of the absolute difference between the exact and approximate solution.")}
load(here::here("data_files/exp_1_f_rect.RData"))
f_rect
```


:::



::: {}


```{r, fig.height = 6, out.width = "100%", fig.cap = captioner("Time evolution of the absolute difference between the exact and approximate solution.")}
load(here::here("data_files/exp_1_f_sphere.RData"))
f_sphere
```


:::


::::





















