---
title: "Something"
date: "Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: show # class.source = "fold-hide" to hide code and add a button to show it
    df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
    code_download: true
    css: visual.css
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
  - \newcommand{\Wcal}{\mathcal{W}}
---

Go back to the [Contents](about.html) page.

<div style="color: #2c3e50; text-align: right;">
********  
<strong>Press Show to reveal the code chunks.</strong>  

********
</div>


```{r, purl = FALSE, echo = FALSE}
# Create a clipboard button on the rendered HTML page
source(here::here("clipboard.R")); clipboard
```


```{r, purl = FALSE, class.source = "fold-hide"}
# Set seed for reproducibility
set.seed(1982) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}
```


```{r}
capture.output(
  knitr::purl(here::here("euclidean_functionality.Rmd"), output = here::here("euclidean_functionality.R")),
  file = here::here("purl_log.txt")
)
source(here::here("euclidean_functionality.R"))
```




```{r}
# Parameters
a <- 1
b <- 1
kappa <- 1
alpha <- 1.5
m = 1
beta <- alpha/2

nx <- 10
ny <- 10
T_final <- 1
time_step <- 0.1 
time_seq <- seq(0, T_final, by = time_step)
coeff <- 1
which_eig <- 4
```


```{r}
FEM_matrices <- fem$fem_shifted_laplacian_sparse(
  a = a,
  b = b, 
  nx = nx, 
  ny = ny, 
  kappa = kappa
  )

L <- FEM_matrices$L
C <- FEM_matrices$C

true_eig <- compute_true_eigen_rectangle(
  a = a, 
  b = b, 
  nx = nx, 
  ny = ny, 
  kappa = kappa,
  m_max = 3, 
  n_max = 3
  )

x <- true_eig$x
y <- true_eig$y
eigvals <- true_eig$eigvals
eigfuncs <- true_eig$eigfuncs
```





```{r}
U_0 <- coeff * eigfuncs[[which_eig]]
U_true <- lapply(exp(-eigvals[which_eig]^(alpha/2) * time_seq), function(x) x * U_0)
```


```{r}
my_op_frac <- my.fractional.operators.frac(L, beta, C, scale.factor = kappa^2, m = m, time_step)


U_aux <- solve_fractional_evolution(my_op_frac, time_step, time_seq, val_at_0 = as.vector(U_0))

U_approx <- result_list <- lapply(seq_len(ncol(U_aux)), function(j) matrix(U_aux[, j], nx+1, ny+1))
```



```{r}
plot_3d_slider(x, y, time_seq, U_true)
```


```{r}
plot_3d_slider(x, y, time_seq, U_approx)
```

```{r}
diff <- Map("-", U_true, U_approx)
plot_3d_slider(x, y, time_seq, diff)
```



