---
title: "On manifolds"
date: "Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: show # class.source = "fold-hide" to hide code and add a button to show it
    df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
    code_download: true
    css: visual.css
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
  - \newcommand{\Wcal}{\mathcal{W}}
---

Go back to the [Contents](about.html) page.

<div style="color: #2c3e50; text-align: right;">
********  
<strong>Press Show to reveal the code chunks.</strong>  

********
</div>


```{r, purl = FALSE, echo = FALSE}
# Create a clipboard button on the rendered HTML page
source(here::here("clipboard.R")); clipboard
```


```{r, purl = FALSE, class.source = "fold-hide"}
# Set seed for reproducibility
set.seed(1982) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}
```


```{r}
capture.output(
  knitr::purl(here::here("manifold_functionality.Rmd"), output = here::here("manifold_functionality.R")),
  file = here::here("purl_log.txt")
)
source(here::here("manifold_functionality.R"))
```




```
{python}
from dolfin import *
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.tri as tri

# --- Mesh and function ---
mesh = UnitSquareMesh(5,5)
V = FunctionSpace(mesh, "Lagrange", 1)

i = 14
phi = Function(V)
phi.vector()[:] = 0.0
phi.vector()[i] = 1.0

# --- Triangulation for plotting ---
coords = mesh.coordinates()
cells = mesh.cells()
triang = tri.Triangulation(coords[:,0], coords[:,1], triangles=cells)

# --- Values at nodes ---
z = phi.vector().get_local()

# --- 3D plot ---
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_trisurf(triang, z, cmap='viridis', edgecolor='k')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('phi')
plt.show()
```

```{r}
# Parameters
a <- 1
b <- 1
kappa <- 4
alpha <- 1.8
m = 4
beta <- alpha/2

nx <- 20
ny <- 20
T_final <- 0.5
time_step <- 0.001
time_seq <- seq(0, T_final, length.out = ((T_final - 0) / time_step + 1))
coeff <- 1
which_eig <- 2
```



```{r}
FEM_matrices <- fem$fem_shifted_laplacian_sparse(
  a = a,
  b = b, 
  nx = nx, 
  ny = ny
  )

C <- FEM_matrices$C
G <- FEM_matrices$G
L <- kappa^2*C + G

x <- FEM_matrices$x
y <- FEM_matrices$y

w_x <- quad_weights(x)
w_y <- quad_weights(y)


true_eig <- compute_true_eigen_rectangle(
  a = a, 
  b = b, 
  x = x, 
  y = y, 
  kappa = kappa,
  m_max = 5, 
  n_max = 5
  )

eigvals <- true_eig$eigvals
eigfuncs <- true_eig$eigfuncs

# Compute the true solution
U_0 <- coeff * eigfuncs[[which_eig]]
U_true_list <- lapply(exp(-(eigvals[which_eig]^(alpha/2)) * time_seq), function(xi) U_0 * xi)
U_true_matrix <- do.call(cbind, lapply(U_true_list, as.vector))
# Compute the approximate solution
my_op_frac <- my.fractional.operators.frac(L, beta, C, scale.factor = kappa^2, m = m, time_step)
U_approx_matrix <- solve_fractional_evolution(my_op_frac, time_step, time_seq, val_at_0 = as.vector(U_0))
U_approx_list <- lapply(1:ncol(U_approx_matrix), function(j) matrix(U_approx_matrix[, j], nrow = length(x), ncol = length(y), byrow = FALSE))
# Compute the error
diff <- Map(function(a, b) abs(a - b), U_true_list, U_approx_list)
error_at_each_time <- sapply(diff, function(M) t(w_x) %*% (M^2) %*% w_y)
total_error <- sqrt(time_step * sum(error_at_each_time))
total_error

XX <- U_true_matrix - U_approx_matrix
error <- sqrt(as.double(time_step * sum(XX * (C %*% XX))))
error

res <- fem$transfer_solution_to_fine(
  V_coarse = FEM_matrices$V,
  U_coarse_matrix = U_true_matrix,
  a = a, 
  b = b,
  nx_fine = 2*nx,
  ny_fine = 2*ny
)

U_true_fine_list <- res$U_fine_list
```


```{r}
# Plot results
plot_3d_slider(x, y, time_seq, U_approx_list) # approximate
plot_3d_slider(x, y, error_at_each_time, diff) # error
plot_3d_slider(res$x_fine, res$y_fine, time_seq, U_true_fine_list) # true in fine mesh
plot_3d_slider(x, y, time_seq, U_true_list) # true in coarse mesh
```

