---
title: "Example on the sphere"
date: "Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: show # class.source = "fold-hide" to hide code and add a button to show it
    df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
    code_download: true
    css: visual.css
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
  - \newcommand{\Wcal}{\mathcal{W}}
---

Go back to the [Contents](about.html) page.

<div style="color: #2c3e50; text-align: right;">
********  
<strong>Press Show to reveal the code chunks.</strong>  

********
</div>


```{r, purl = FALSE, echo = FALSE}
# Create a clipboard button on the rendered HTML page
source(here::here("clipboard.R")); clipboard
```


```{r, purl = FALSE, class.source = "fold-hide"}
# Set seed for reproducibility
set.seed(1982) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}
```


```{r}
capture.output(
  knitr::purl(here::here("manifold_functionality.Rmd"), output = here::here("manifold_functionality.R")),
  file = here::here("purl_log.txt")
)
source(here::here("manifold_functionality.R"))
```


```{r}
library(fmesher)
library(Matrix)
```


```{r}
T_final <- 2
kappa <- 4


L_max <- 2
rot.inv <- TRUE


coeff_U_0 <- rep(0, L_max+1)
coeff_U_0[3] <- 1
coeff_FF <- rep(0, L_max+1)
coeff_FF[2] <- 10


AAA = 1
OMEGA = pi

alpha <- 1.8
m = 4
beta <- alpha/2


time_step <- 0.001
time_seq <- seq(0, T_final, length.out = ((T_final - 0) / time_step + 1))

globe_coarse <- 5
globe_fine <- 2*globe_coarse
```



```{r}
mesh_coarse <- fm_rcdt_2d(globe = globe_coarse)
FEM_coarse <- fm_fem(mesh_coarse, order = 1)
C <- FEM_coarse$c1
G <- FEM_coarse$g1
L <- kappa^2 * C + G

eig <- compute_true_eigen_sphere(
  mesh = mesh_coarse, 
  kappa = kappa, 
  L_max = L_max, 
  rot.inv = rot.inv)
EIGENVAL_ALPHA <- eig$EIGENVAL_ALPHA
EIGENFUN <- eig$EIGENFUN
U_0 <- EIGENFUN %*% coeff_U_0
U_true <- EIGENFUN %*% 
    outer(1:length(coeff_U_0), 
          1:length(time_seq), 
          function(i, j) (coeff_U_0[i] + coeff_FF[i] * G_sin(t = time_seq[j], A = AAA, lambda_j_alpha_half = EIGENVAL_ALPHA[i], omega = OMEGA)) * exp(-EIGENVAL_ALPHA[i] * time_seq[j]))
```



```{r}
mesh_fine <- fm_rcdt_2d(globe = globe_fine)
FEM_fine <- fm_fem(mesh_fine, order = 1)
Psi <- fm_basis(mesh_coarse, mesh_fine$loc)

eig_fine <- compute_true_eigen_sphere(
  mesh = mesh_fine, 
  kappa = kappa, 
  L_max = L_max, 
  rot.inv = rot.inv)
EIGENFUN_fine <- eig_fine$EIGENFUN

FF_approx <- t(Psi) %*% 
  FEM_fine$c1 %*%
  EIGENFUN_fine %*%
      outer(1:length(coeff_FF), 
            1:length(time_seq), 
        function(i, j) coeff_FF[i] * g_sin(r = time_seq[j], A = AAA, omega = OMEGA))

my_op_frac <- my.fractional.operators.frac(L, beta, C, scale.factor = kappa^2, m = m, time_step)
U_approx <- solve_fractional_evolution(my_op_frac, time_step, time_seq, val_at_0 = U_0, RHST = FF_approx)


diff <- U_true - U_approx
error <- sqrt(as.double(time_step * sum(diff * (C %*% diff))))
error
```



```{r, fig.height = 6, out.width = "100%", fig.cap = captioner("Time evolution of the absolute difference between the exact and approximate solution.")}
# Plot results
idx <- which.min(abs(time_seq - 1))
plot_3d_slider_sphere_scatter(mesh_coarse, time_seq[1:2], U_true[,1:2], fixed_colorscale = FALSE)
```





















