---
title: "On manifolds"
date: "Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: show # class.source = "fold-hide" to hide code and add a button to show it
    df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
    code_download: true
    css: visual.css
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
  - \newcommand{\Wcal}{\mathcal{W}}
---

Go back to the [Contents](about.html) page.

<div style="color: #2c3e50; text-align: right;">
********  
<strong>Press Show to reveal the code chunks.</strong>  

********
</div>


```{r, purl = FALSE, echo = FALSE}
# Create a clipboard button on the rendered HTML page
source(here::here("clipboard.R")); clipboard
```


```{r, purl = FALSE, class.source = "fold-hide"}
# Set seed for reproducibility
set.seed(1982) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}
```


```{r}
capture.output(
  knitr::purl(here::here("manifold_functionality.Rmd"), output = here::here("manifold_functionality.R")),
  file = here::here("purl_log.txt")
)
source(here::here("manifold_functionality.R"))
```


```{r}
library(fmesher)
library(Matrix)
```


```{r}
kappa <- 4
a <- 100
b <- 100

alpha <- 1.8
m = 4
beta <- alpha/2

T_final <- 0.5
time_step <- 0.01
time_seq <- seq(0, T_final, length.out = ((T_final - 0) / time_step + 1))
overkill_time_step <- 0.001
overkill_time_seq <- seq(0, T_final, length.out = ((T_final - 0) / overkill_time_step + 1))

nx_coarse <- 25
ny_coarse <- 25
nx_fine <- 2*nx_coarse
ny_fine <- 2*ny_coarse

m_max <- 2
n_max <- 2
N_eig <- (m_max + 1) * (n_max + 1)
coeff_U_0 <- rep(0, N_eig)
coeff_U_0[9] <- 1
coeff_FF <- rep(0, N_eig)
coeff_FF[2] <- 10

AAA = 1
OMEGA = pi
```


```{r}
x_fine <- seq(0, a, length.out = nx_fine + 1)
y_fine <- seq(0, b, length.out = ny_fine + 1)
lattice_fine <- fm_lattice_2d(
  x = x_fine,
  y = y_fine
)

mesh_fine <- fm_rcdt_2d(
  lattice = lattice_fine,
  extend = FALSE
)
plot(mesh_fine)
```



```{r}
eig_fine <- compute_true_eigen_rectangle(
  a = a, 
  b = b, 
  loc = mesh_fine$loc,
  kappa = kappa,
  m_max = m_max, 
  n_max = n_max
)

eigvals <- eig_fine$eigvals
eigfuncs_fine <- eig_fine$eigfuncs


U_true <- eigfuncs_fine %*% 
    outer(1:length(coeff_U_0), 
          1:length(overkill_time_seq), 
          function(i, j) (coeff_U_0[i] + coeff_FF[i] * G_sin(t = overkill_time_seq[j], A = AAA, lambda_j_alpha_half = eigvals[i]^(alpha/2), omega = OMEGA)) * exp(-(eigvals[i]^(alpha/2)) * overkill_time_seq[j]))
  
```


```{r}
x_coarse <- seq(0, a, length.out = nx_coarse + 1)
y_coarse <- seq(0, b, length.out = ny_coarse + 1)

lattice_coarse <- fm_lattice_2d(
  x = x_coarse,
  y = y_coarse
)

mesh_coarse <- fm_rcdt_2d(
  lattice = lattice_coarse,
  extend = FALSE
)
plot(mesh_coarse)
```



```{r}
FEM_coarse <- fm_fem(mesh_coarse, order = 1)
Cl <- FEM_coarse$c0
C <- FEM_coarse$c1
G <- FEM_coarse$g1
L <- kappa^2 * C + G
Psi <- fm_basis(mesh_coarse, mesh_fine$loc)
C_fine <- fm_fem(mesh_fine, order = 1)$c1
```




```{r}
eig_coarse <- compute_true_eigen_rectangle(
  a = a, 
  b = b, 
  loc = mesh_coarse$loc,
  kappa = kappa,
  m_max = m_max, 
  n_max = n_max
)
eigfuncs_coarse <- eig_coarse$eigfuncs
```



```{r}
U_0_coarse <- eigfuncs_coarse %*% coeff_U_0
INT_BASIS_EIGEN <- t(eigfuncs_fine) %*% C_fine %*% Psi
# Compute matrix F with columns F^k
FF_approx <- t(INT_BASIS_EIGEN) %*% 
      outer(1:length(coeff_FF), 
            1:length(time_seq), 
        function(i, j) coeff_FF[i] * g_sin(r = time_seq[j], A = AAA, omega = OMEGA))

FF_true <- eigfuncs_coarse %*% outer(1:length(coeff_FF), 
                         1:length(time_seq), 
                         function(i, j) coeff_FF[i] * g_sin(r = time_seq[j], A = AAA, omega = OMEGA))
```


```{r}
my_op_frac <- my.fractional.operators.frac(L, beta, C, scale.factor = kappa^2, m = m, time_step)
U_approx <- solve_fractional_evolution(my_op_frac, time_step, time_seq, val_at_0 = U_0_coarse, RHST = FF_approx)

U_approx_proj <- Psi %*% U_approx
U_approx_proj <- construct_piecewise_projection(U_approx_proj, time_seq, overkill_time_seq)
diff <- U_true - U_approx_proj

error <- sqrt(as.double(overkill_time_step * sum(diff * (C_fine %*% diff))))
error
```



```{r}
# Plot results
plot_3d_slider_scatter(mesh_fine$loc, overkill_time_seq, U_true)
plot_3d_slider_scatter(mesh_coarse$loc, time_seq, U_approx)
plot_3d_slider_scatter(mesh_fine$loc, overkill_time_seq, U_approx_proj)
plot_3d_slider_scatter(mesh_fine$loc, overkill_time_seq, abs(diff))
plot_3d_slider_scatter(mesh_coarse$loc, time_seq, eigfuncs_coarse)
plot_3d_slider_scatter(mesh_coarse$loc, time_seq, FF_true)
```





















